version: "3.3"
services:
  zookeeper1:
      image: 'registry.aliyuncs.com/acs-sample/zookeeper:3.4.8'
      container_name: zookeeper1
      ports:
          - "2181:2181"
      environment:
          - SERVER_ID=1
          - ADDITIONAL_ZOOKEEPER_1=server.1=0.0.0.0:2888:3888
          - ADDITIONAL_ZOOKEEPER_2=server.2=zookeeper2:2888:3888 
          - ADDITIONAL_ZOOKEEPER_3=server.3=zookeeper3:2888:3888
  zookeeper2:
      image: 'registry.aliyuncs.com/acs-sample/zookeeper:3.4.8'
      container_name: zookeeper2
      ports:
          - "2182:2181"
      environment:
          - SERVER_ID=2
          - ADDITIONAL_ZOOKEEPER_1=server.1=zookeeper1:2888:3888
          - ADDITIONAL_ZOOKEEPER_2=server.2=0.0.0.0:2888:3888 
          - ADDITIONAL_ZOOKEEPER_3=server.3=zookeeper3:2888:3888
  zookeeper3:
      image: 'registry.aliyuncs.com/acs-sample/zookeeper:3.4.8'
      container_name: zookeeper3
      ports:
          - "2183:2181"
      environment:
          - SERVER_ID=3
          - ADDITIONAL_ZOOKEEPER_1=server.1=zookeeper1:2888:3888
          - ADDITIONAL_ZOOKEEPER_2=server.2=zookeeper2:2888:3888 
          - ADDITIONAL_ZOOKEEPER_3=server.3=0.0.0.0:2888:3888
  kafka1:
    image: 'wurstmeister/kafka'
    container_name: kafka1
    ports:
      - "9091:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
  kafka2:
    image: 'wurstmeister/kafka'
    container_name: kafka2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
  kafka3:
    image: 'wurstmeister/kafka'
    container_name: kafka3
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
